spring:
  application:
    name: cow_mvc_practice
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  datasource:
    url: jdbc:tc:mysql:8.0.36://cow/mydatabase?
    username: myuser
    password: secret
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  docker:
    compose:
      file: compose.yaml
      enabled: true
      lifecycle-management: none
      start:
        command: up
      stop:
        command: down
        timeout: 1m

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8081